<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>89acf56a-4486-41ef-a150-e94a8a707391</testSuiteGuid>
   <testCaseLink>
      <guid>5f431b13-7bc4-45f0-a922-49bf0792279c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Fullname Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>335556ab-752c-416e-8c24-3bb70a796adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d7cd1a-ec4e-4e9a-9b91-b6383ce55cee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>789549a1-afe2-45f0-96d2-ba15de8462fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93a9e013-baa3-462f-9621-30c5c46eb74b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b964b0-79cb-4521-b57b-172259ff967e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69d19fc6-7bd4-4a42-8675-4029da452aa4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Camel Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0880ab92-af23-49c0-8c78-b7e4f7d20ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f209fb-4605-4e70-b58f-6f4e0273a14a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>167d56ca-5ae0-47b5-a434-6727abb2c885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78793de1-2ae5-4213-b855-cfc50b8f0ca0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>325a4cd1-2d45-4b66-882e-08d4abf48fd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f27d38f5-c5d9-4716-91cf-91a1cc889901</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Combination</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc6e2f86-a8ca-43b6-a613-06bac0173b29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ca1637d-599e-488d-b09b-036fa6fd7d40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d529cec7-7a20-4964-ade4-fb0cf2b6f22a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Lowercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61570c5-42ad-4ee1-9f92-99fd74b6c07f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3051f8bb-fb4f-47d5-914a-f1a85dc392a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c53a7098-1b2d-4832-9191-7b3fd32c234b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b314fb-6453-455b-962f-775c7909e14f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dd3566e-0009-4e8d-b6b8-b86f17215b29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fac45bd5-213c-458c-b58b-ce2b5959fd9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Uppercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8aced7-d8a0-41fd-ae38-e2d57a157f0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc02294c-5729-43f1-86ce-95fd08bf9f86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c8a8ee4-2f6f-402b-979c-90422ee68d19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Using Space</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4739642a-bab9-49e2-9835-0dd83f6d6c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b025d0-1d68-42fa-a9fb-c06f6616535a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6219f370-95fc-4864-b9ed-b112531fb12b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Negative/Input Only Space</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ceeff92-5917-4bb6-87d9-a7ca996ea3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6b70c02-2df9-4866-8b8d-c48b919ea071</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b713de5-6687-49ea-82ce-dddf26ec7bbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/Data-driven Testing/DDT - Fullname</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e735034-ab1c-4c23-8c67-6f343e13db07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5191e838-fb6a-444e-b63f-dff1a096dc12</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
