<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>63ce22ec-c560-4122-a724-8ed13abc7717</testSuiteGuid>
   <testCaseLink>
      <guid>4fd7848d-5463-4928-b509-b711c654c09f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Fullname Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>335556ab-752c-416e-8c24-3bb70a796adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d7cd1a-ec4e-4e9a-9b91-b6383ce55cee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81a6ca26-4fa8-4d5a-a40e-a7e337769aee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93a9e013-baa3-462f-9621-30c5c46eb74b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b964b0-79cb-4521-b57b-172259ff967e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e519ed14-26ed-42d0-a813-07f51592d25b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Camel Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0880ab92-af23-49c0-8c78-b7e4f7d20ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f209fb-4605-4e70-b58f-6f4e0273a14a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6e5138c-4b40-422d-8d38-e7c0863f3ddc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78793de1-2ae5-4213-b855-cfc50b8f0ca0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>325a4cd1-2d45-4b66-882e-08d4abf48fd1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2cb344a-e47a-48cd-bb96-d04d4c8978cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Combination</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc6e2f86-a8ca-43b6-a613-06bac0173b29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ca1637d-599e-488d-b09b-036fa6fd7d40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7a49d57-1b96-423d-9fb7-a8a1731f6e4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Lowercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61570c5-42ad-4ee1-9f92-99fd74b6c07f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3051f8bb-fb4f-47d5-914a-f1a85dc392a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d13a7dbb-4d32-4a48-8b61-d42e9f96f939</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b314fb-6453-455b-962f-775c7909e14f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dd3566e-0009-4e8d-b6b8-b86f17215b29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff1d3abf-51eb-49e7-9e28-82780e0aef29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Uppercase</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8aced7-d8a0-41fd-ae38-e2d57a157f0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc02294c-5729-43f1-86ce-95fd08bf9f86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec4773ca-b94a-4f1d-a940-bdbd11ffe69b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Fullname/StudioAssist/Positive/Input Using Space</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4739642a-bab9-49e2-9835-0dd83f6d6c10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36b025d0-1d68-42fa-a9fb-c06f6616535a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
