<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>285fb4f0-ccdc-41de-bae7-d16d1ce8686d</testSuiteGuid>
   <testCaseLink>
      <guid>fdc2ad8c-be6a-47b3-8363-4e21a1632f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Email Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad3eac6-9526-4e71-9af4-dc03909fc022</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f27e075d-f991-4879-b4c7-85b1edc19615</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>806d057f-8548-4bd6-b3d2-fb2986800029</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Acceptable Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ca7ee23-d6c7-452d-8d81-bc551b0e9b14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96777982-6136-4a90-bad1-35708d0fc4dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b951c7fb-fef4-4a8c-ad53-5781b414b1f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ca80eb-cbf9-426e-b428-46de7b50623c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d012e89-3d32-4a78-bcbf-89827fbf8707</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b78bd5ce-9968-42fa-898a-fa49b93e906c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>708124ac-47e8-4483-b4d0-ea3fadb5370c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81eafe2d-46d8-4583-9f06-13013f99d3f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5842d3d-8f01-48ae-a483-e83e8bbb16a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Using Forbidden Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ea56b9a-c16a-4ad1-8129-2121dd67ab26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c9a2bfe-ef6b-4ae3-bdd8-fce1f2423212</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd0e181b-2c92-448a-b0a6-863eeaade316</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without AT Sign</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f44ef3cc-79ed-4bbd-84f1-2502ac253891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71efa7bc-308f-477d-a282-dee841005f24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4c8f612-cdac-4619-8ede-2bcd959ae15b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without Domain</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f16beae-9634-4f3e-a1e1-3c9e5ff48c0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f0ba72-835c-4bb6-8e06-abe5211f3164</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dde73df9-04a2-48ab-9db9-ffa5fa5b2900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without Site Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7dd63f5-cd80-4f4f-95d9-6612bb2712ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e0a25d-5ac6-4c4e-a48b-55b46bc1e90b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46a36aca-774e-485a-9cef-b67c6d7bb090</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Data-driven Testing/DDT - Email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d38d3534-48b8-4c8e-9c69-03a9ec694c20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dad134e-5677-4e48-891c-6c08b674d7ef</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
