<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b8bfc096-8cc4-4978-9d56-556e3fa5ce2f</testSuiteGuid>
   <testCaseLink>
      <guid>d484c67c-e156-4132-9f6b-8473c5ad0efa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Using Forbidden Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ea56b9a-c16a-4ad1-8129-2121dd67ab26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c9a2bfe-ef6b-4ae3-bdd8-fce1f2423212</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9c62741-327e-4048-ac05-747e9166d39d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without AT Sign</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f44ef3cc-79ed-4bbd-84f1-2502ac253891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71efa7bc-308f-477d-a282-dee841005f24</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e56ce456-2342-4dfc-a629-f58e6e607005</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without Domain</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f16beae-9634-4f3e-a1e1-3c9e5ff48c0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81f0ba72-835c-4bb6-8e06-abe5211f3164</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fcd92f7e-ac46-4b14-80b4-84e032fbcff7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Negative/Without Site Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7dd63f5-cd80-4f4f-95d9-6612bb2712ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e0a25d-5ac6-4c4e-a48b-55b46bc1e90b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
