<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e426c6b8-4a7c-4160-ab89-8a3e12e9a61f</testSuiteGuid>
   <testCaseLink>
      <guid>958fe446-9cfd-4b75-b778-5fcc48a77ed8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Email Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ad3eac6-9526-4e71-9af4-dc03909fc022</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f27e075d-f991-4879-b4c7-85b1edc19615</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50beff08-3c79-43f1-8ae7-61c417c2c7bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Acceptable Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ca7ee23-d6c7-452d-8d81-bc551b0e9b14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96777982-6136-4a90-bad1-35708d0fc4dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8913a786-fb17-477b-90b7-555dafed156c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ca80eb-cbf9-426e-b428-46de7b50623c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d012e89-3d32-4a78-bcbf-89827fbf8707</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e83982a-d439-4c10-8eb4-f245bc1f826c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/demoqa/Element/Textbox/Email/Positive/Using Number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>708124ac-47e8-4483-b4d0-ea3fadb5370c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81eafe2d-46d8-4583-9f06-13013f99d3f9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
